import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Budgetly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.className} h-full antialiased`}
    >
      <body className="min-h-full bg-gray-50">
        <ClerkProvider>
          <TooltipProvider>  
            {children}
          </TooltipProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
